language: python
python:
  - "3.6"
# command to install dependencies
install:
  - pip install -e . 
  - pip install sphinx==1.6.5 recommonmark sphinx_rtd_theme pyyaml coveralls
# command to run tests
script:
  - cd docs && make html
  - python -m fluids --time 100 -v 0 -o birdseye
  - python -m fluids --time 100 -v 0 -o grid
  - python -m fluids --time 100 -v 0 -o none
  - coverage run -a --source fluids -m fluids --time 100 -v 0 -o birdseye
  - coverage run -a --source fluids -m fluids --time 100 -v 0 -o grid
  - coverage run -a --source fluids -m fluids --time 100 -v 0 -o none

after_success:
  - coveralls


