language: python
python:
  - "3.6"
# command to install dependencies
install:
  - pip install -e .
  - pip install sphinx==1.6.5 recommonmark sphinx_rtd_theme
# command to run tests
script:
  - cd docs && make html

