language: python
python:
  - "3.6"
# command to install dependencies
install:
  - pip install -e .
  - pip install sphinx==1.6.5 recommonmark sphinx_rtd_theme
# command to run tests
script:
  - python tests/test_velocity_action.py # or py.test for Python versions 3.5 and below
  - python tests/test_simulator_step.py # or py.test for Python versions 3.5 and below
  - python tests/test_simulator_multiple_steps.py # or py.test for Python versions 3.5 and below
  - python tests/test_json_agents_init.py # or py.test for Python versions 3.5 and below
  - python tests/test_render.py #or py.test for Python versions 3.5 and below
  - python tests/test_supervisor.py #or py.test for Python version 3.5 and below
  - python tests/test_q_lidar.py #or py.test for Python version 3.5 and below
  - python tests/test_traj_class.py #or py.test for Python version 3.5 and below
  - python tests/test_pedestrians.py #or py.test for Python version 3.5 and below
  - python tests/test_neural_velocity_supervisor.py
  - python tests/test_neural_velocity_background_agent.py
  - python tests/test_array_state.py
  - cd docs && make html

after_success:
  - codecov

